### PR TITLE
add version 1.15

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@maresb I'm happy to add myself as a maintainer if you want some help with this package, I need this version due to this bug in another package: https://github.com/Zsailer/sphinx-pydantic/issues/5

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Thanks @mikemhenry! Older versions are usually done on a branch in order to keep the history in `main` clean. Thus I merged it into the `v1.15` branch. Glad to have you here as a maintainer!

**Comment by mikemhenry** [comment]
@maresb Thanks!

**Comment by maresb** [comment]
It's now installable.

**Pull request merged**
